[project]
name = "dockerdb-backups-restore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.17.0",
    "pyqt6>=6.10.0",
]
